### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by Doofitator** [BenDavidson90/batterybar-win10battery#1]
As of Windows 1903, there is the option to set windows' taskbar and start menu to a light theme, which causes the battery icon to be illegible.

**Comment by bsdev90** [comment]
Hi @Doofitator , after testing the light theme, I see you're right. I'll try to make a light theme as soon as I can, probably within a week.

**Comment by Doofitator** [comment]
Awesome! Thanks for the quick response - I'll look out for the update!

**Comment by bsdev90** [comment]
Done!
Feel free to tell me what you think of this update :)

![preview](https://user-images.githubusercontent.com/7091140/73493207-93bb8080-43b2-11ea-83fd-8f0e84b7da3e.png)
